name: Publish Docker image

on:
  release:
    types: [ published ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set tag env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: adopt

      - name: Build Docker Image
        run: |-
          ./gradlew clean dockerbuild
          docker tag clowre/docserver clowre/docserver:$RELEASE_VERSION

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push docker image
        run: docker push clowre/docserver:$RELEASE_VERSION
